dist: trusty
language: node_js
node_js:
  - "10"
services:
  - mongodb
  - rabbitmq
before_install:
  - echo "install"
  - chmod +x ./shells/env-config.sh
  - ./shells/env-config.sh
install:
  - npm install
before_script:
  - "echo script"
script:
  - npm run test
  - echo done
