dist: trusty
language: node_js
node_js:
  - "10"
services:
  - mongodb
  - rabbitmq
before_install:
  - echo "install"
  - find . -name ".env.sample" -execdir cp {} .env \; 
install:
  - npm install
before_script:
  - "echo script"
script:
  - npm run test
  - echo done
