dist: trusty
matrix:
  include:
    - language: node_js
      node_js: 10
      before_script:
        - "echo before script"
      install:
        - npm install
      script:
        - npm run test


  include:
    - language: python
      python: 3.4
      before_script:
        - echo "before script for python"
      install:
        - echo "installing python deps"
      script:
        - echo "running py tests"
